services:
  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_DB: "rb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  redis:
    container_name: "redis"
    image: redis
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local