spring:
  application:
    name: pioneer-api
  jpa:
    open-in-view: false
  datasource:
    username: "postgres"
    password: "1"
    url: jdbc:postgresql://localhost:5432/rb
jwt:
  secret-key: 4bca76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration-time: 3600000
